version: "3"

services:
  chatglm:
    build: ./python
    container_name: chatglm_api
    hostname: chatglm_api
    restart: unless-stopped
    shm_size: '2gb'
    port:
      - 8888:8888
    volumes:
      - ./models:/opt/models:ro
    networks:
      - app

  web:
    image: yidadaa/chatgpt-next-web
    hostname: web
    depends_on:
      - chatglm
    port:
      - 8000:3000
    environment:
      BASE_URL: "http://172.17.0.1:8888"
      OPENAI_API_KEY: "not-needed"
    restart: unless-stopped
    networks:
      - app

networks:
  app:
